export const rowsAndTickets = [
  [
    { id: 1, occupied: true, selected: false },
    { id: 2, occupied: true, selected: false },
    { id: 3, occupied: false, selected: false },
    { id: 4, occupied: false, selected: false },
    { id: 5, occupied: true, selected: false },
    { id: 6, occupied: true, selected: false },
    { id: 7, occupied: true, selected: false },
    { id: 8, occupied: false, selected: false },
    { id: 9, occupied: false, selected: false },
    { id: 10, occupied: false, selected: false },
    { id: 11, occupied: true, selected: false },
  ],
  [
    { id: 12, occupied: false, selected: false },
    { id: 13, occupied: false, selected: false },
    { id: 14, occupied: false, selected: false },
    { id: 15, occupied: true, selected: false },
    { id: 16, occupied: false, selected: false },
    { id: 17, occupied: false, selected: false },
    { id: 18, occupied: false, selected: false },
    { id: 19, occupied: false, selected: false },
    { id: 20, occupied: false, selected: false },
    { id: 21, occupied: false, selected: false },
    { id: 22, occupied: false, selected: false },
  ],
  [
    { id: 23, occupied: false, selected: false },
    { id: 24, occupied: false, selected: false },
    { id: 25, occupied: true, selected: false },
    { id: 26, occupied: true, selected: false },
    { id: 27, occupied: false, selected: false },
    { id: 28, occupied: false, selected: false },
    { id: 29, occupied: false, selected: false },
    { id: 30, occupied: false, selected: false },
    { id: 31, occupied: false, selected: false },
    { id: 32, occupied: false, selected: false },
    { id: 33, occupied: false, selected: false },
  ],
  [
    { id: 34, occupied: false, selected: false },
    { id: 35, occupied: false, selected: false },
    { id: 36, occupied: false, selected: false },
    { id: 37, occupied: false, selected: false },
    { id: 38, occupied: true, selected: false },
    { id: 39, occupied: true, selected: false },
    { id: 40, occupied: false, selected: false },
    { id: 41, occupied: true, selected: false },
    { id: 42, occupied: false, selected: false },
    { id: 43, occupied: false, selected: false },
    { id: 44, occupied: false, selected: false },
  ],
  [
    { id: 45, occupied: false, selected: false },
    { id: 46, occupied: false, selected: false },
    { id: 47, occupied: false, selected: false },
    { id: 48, occupied: false, selected: false },
    { id: 49, occupied: true, selected: false },
    { id: 50, occupied: false, selected: false },
    { id: 51, occupied: false, selected: false },
    { id: 52, occupied: false, selected: false },
    { id: 53, occupied: false, selected: false },
    { id: 54, occupied: false, selected: false },
    { id: 55, occupied: false, selected: false },
  ],
  [
    { id: 56, occupied: false, selected: false },
    { id: 57, occupied: false, selected: false },
    { id: 58, occupied: false, selected: false },
    { id: 59, occupied: false, selected: false },
    { id: 60, occupied: false, selected: false },
    { id: 61, occupied: false, selected: false },
    { id: 62, occupied: false, selected: false },
    { id: 63, occupied: false, selected: false },
    { id: 64, occupied: false, selected: false },
    { id: 65, occupied: false, selected: false },
    { id: 66, occupied: false, selected: false },
  ],
  [
    { id: 67, occupied: false, selected: false },
    { id: 68, occupied: true, selected: false },
    { id: 69, occupied: false, selected: false },
    { id: 70, occupied: true, selected: false },
    { id: 71, occupied: true, selected: false },
    { id: 72, occupied: false, selected: false },
    { id: 73, occupied: false, selected: false },
    { id: 74, occupied: false, selected: false },
    { id: 75, occupied: false, selected: false },
    { id: 76, occupied: true, selected: false },
    { id: 77, occupied: false, selected: false },
  ],
  [
    { id: 78, occupied: false, selected: false },
    { id: 79, occupied: true, selected: false },
    { id: 80, occupied: false, selected: false },
    { id: 81, occupied: false, selected: false },
    { id: 82, occupied: true, selected: false },
    { id: 83, occupied: false, selected: false },
    { id: 84, occupied: false, selected: false },
    { id: 85, occupied: false, selected: false },
    { id: 86, occupied: false, selected: false },
    { id: 87, occupied: false, selected: false },
    { id: 88, occupied: true, selected: false },
  ],
]
